spring.application.name=spring-plantilla
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.security.jwt.secret=${JWT_TOKEN}
spring.security.jwt.expiration=${JWT_EXPIRATION}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.swagger-ui.path=/api/docs
spring.jpa.open-in-view=false
spring.mail.properties.mail.smtp.starttls.required=true
# springfox.documentation.enabled=false 
# Deshabilitar swagger en producción
# 2FA TOTP issuer name (visible en Google Authenticator)
totp.issuer=SpringAPI